version: '3.7'
services:
    tetris:
        image: 'node:13'
        user: 'node'
        tty: true
        command: >
            bash -c "npm install &&
                    ./node_modules/.bin/webpack &&
                     npm run srv-dev"
        container_name: 'tetris_node'
        working_dir: '/home/node/project'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:4433']
            interval: '10s'
            timeout: '10s'
            retries: 3
            start_period: '40s'
        volumes:
            -
                source: '.'
                target: '/home/node/project'
                type: 'bind'
                consistency: 'delegated'
        ports:
            -
                mode: 'host'
                target: 4433
                published: 4433
                protocol: 'tcp'
            -
                mode: 'host'
                target: 4433
                published: 4433
                protocol: 'udp'
